### ISSUE TITLE
GLLineWidth Doesn't Work

### ISSUE THREAD

**Issue by jbhav24** [lapfelix/ARKit-line-drawing#4]
When you change the integer within GLLineWidth(x) it doesn't work on changing the actual line.

**Comment by lapfelix** [comment]
Ah yes it looks like it doesn't work with every value: https://stackoverflow.com/a/30362579/2963024

Also it seems like the SceneKit renderer isn't required by OpenGL standards to actually implement a line width greater than 1.

**Comment by WillBishop** [comment]
I can't get it to work at all, no matter the value

**Comment by jbhav24** [comment]
@WillBishop I suggest creating a SCNNode that is a cylinder using the coordinates that you have access to. This will allow you to have a lot more customizability in terms of how you can edit such variables.
