### ISSUE TITLE
Trouble building in xcode 9 beta 2

### ISSUE THREAD

**Issue by jamieomatthews** [lapfelix/ARKit-line-drawing#7]
I'm getting an error building the project in Xcode 9 beta 2.  The error I'm getting is 
"SCNMatrix4FromMat4 is unavailable in swift" viewController line 67

**Comment by lapfelix** [comment]
Ah, yes! Thank you

Fixed that by accessing the camera's transform in `SCNMatrix4` format directly from the `pointOfView` variable.
